apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: console
      port: 80
      targetPort: console
    - name: api
      port: 9000
      targetPort: api
