kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-storage
  labels:
    app: minio
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
