apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: convertx-data
  labels:
    app: convertx
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
