apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: prometheus
      containers:
        - name: promtail
          image: grafana/promtail:latest
          args:
            - "-config.file=/mnt/config/promtail-config.yml"
          ports:
            - name: promtail
              containerPort: 9080
          env: 
          - name: 'HOSTNAME'
            valueFrom:
              fieldRef:
                fieldPath: 'spec.nodeName'
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: promtail-config
              mountPath: /mnt/config
            - name: promtail-storage
              mountPath: /var/lib/promtail
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: promtail-config
          configMap:
            name: promtail-config
        - name: promtail-storage
          persistentVolumeClaim:
            claimName: promtail-storage

