kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: promtail-storage
  labels:
    app: promtail
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
