---
- hosts: servers
  become: yes
  vars_files:
    - ./../../vars/main.yml
  roles:
  - prometheus.prometheus.node_exporter
  vars:
    node_exporter_basic_auth_users:
      prom: "{{ prometheus_node_exporter_password }}"
