---
- hosts: admin
  become: yes
  vars_files:
    - ./../../vars/main.yml
  roles:
  - prometheus.prometheus.prometheus
  - prometheus.prometheus.alertmanager # configure basic auth
  vars:
    alertmanager_version: latest
    alertmanager_receivers:
      - name: discord
        discord_configs:
          - send_resolved: true
            webhook_url: "{{ alertmanager_discord_webhook_url }}"
    alertmanager_route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: discord

    # prometheus
    prometheus_alertmanager_config:
    - scheme: http
      basic_auth:
        username: prom
        password: "{{ alertmanager_password }}"
      static_configs:
        - targets: ["{{ inventory_hostname }}:9093"]
    prometheus_targets:
      node:
      - targets:
        - 192.168.100.2:9100
        - 64.23.177.184:9100
    prometheus_scrape_configs:
      - job_name: "node"
        basic_auth:
          username: prom
          password: "{{ prometheus_node_exporter_password }}"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/node.yml"
