apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdfding-storage
  labels:
    app: pdfding
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdfding-media
  labels:
    app: pdfding
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
