apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-storage
  labels:
    app: mariadb
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
