apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          env:
            - name: TZ
              value: "Asia/Amman"
          volumeMounts:
            - name: home-assistant-config
              mountPath: /config 
          ports:
            - name: http
              containerPort: 8123
      volumes:
        - name: home-assistant-config
          configMap:
            name: home-assistant-config
