groups:
- name: cpu
  rules:
  - alert: HighNodeCPU
    expr: 100 - (avg by (node) (irate(node_cpu_seconds_total{job="node-exporter", mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: critical
      type: cpu
    annotations:
      summary: "Node {{ $labels.node }} CPU utilization is over 80% for last 5 minute"
      description: "CPU on {{ $labels.node }} is averaging {{ $value | humanizePercentage }}"
