groups:
- name: system
  rules:
  - alert: NodeFilesystemSpaceFillingUp
    annotations:
      description: 'Filesystem on {{ $labels.device }} at {{ $labels.node }} has only {{ printf "%.2f" $value }}% available space left and is filling up.'
      summary: 'Filesystem is predicted to run out of space within the next 24 hours.'
    expr: |
      (
        node_filesystem_avail_bytes{job='node-exporter', fstype!=''} 
        / 
        node_filesystem_size_bytes{job='node-exporter', fstype!=''} 
        * 
        100 
        < 
        40 
        and 
        predict_linear(node_filesystem_avail_bytes{job='node-exporter', fstype!=''}[6h], 24*60*60) 
        < 
        0 
        and 
        node_filesystem_readonly{job='node-exporter', fstype!=''} 
        == 
        0
      )
    for: 1h
    labels:
      severity: warning

  - alert: NodeFilesystemAlmostOutOfSpace
    annotations:
      description: 'Filesystem on {{ $labels.device }} at {{ $labels.node }} has only {{ printf "%.2f" $value }}% available space left.'
      summary: 'Filesystem has less than 5% space left.'
    expr: |
      (
        node_filesystem_avail_bytes{job='node-exporter', fstype!=''} 
        / 
        node_filesystem_size_bytes{job='node-exporter', fstype!=''} 
        * 
        100 
        < 
        5 
        and 
        node_filesystem_readonly{job='node-exporter', fstype!=''} 
        == 
        0
      )
    for: 1h
    labels:
      severity: warning

  - alert: NodeFilesystemFilesFillingUp
    annotations:
      description: 'Filesystem on {{ $labels.device }} at {{ $labels.node }} has only {{ printf "%.2f" $value }}% available inodes left and is filling up.'
      summary: 'Filesystem is predicted to run out of inodes within the next 24 hours.'
    expr: |
      (
        node_filesystem_files_free{job='node-exporter', fstype!=''} 
        / 
        node_filesystem_files{job='node-exporter', fstype!=''} 
        * 
        100 
        < 
        40 
        and 
        predict_linear(node_filesystem_files_free{job='node-exporter', fstype!=''}[6h], 24*60*60) 
        < 
        0 
        and 
        node_filesystem_readonly{job='node-exporter', fstype!=''} 
        == 
        0
      )
    for: 1h
    labels:
      severity: warning

  - alert: NodeFilesystemAlmostOutOfFiles
    annotations:
      description: 'Filesystem on {{ $labels.device }} at {{ $labels.node }} has only {{ printf "%.2f" $value }}% available inodes left.'
      summary: 'Filesystem has less than 5% inodes left.'
    expr: |
      (
        node_filesystem_files_free{job='node-exporter', fstype!=''} 
        / 
        node_filesystem_files{job='node-exporter', fstype!=''} 
        * 
        100 
        < 
        5 
        and 
        node_filesystem_readonly{job='node-exporter', fstype!=''} 
        == 
        0
      )
    for: 1h
    labels:
      severity: warning
