groups:
- name: memory
  rules:
  - alert: NodeHighMemoryUsage
    expr: (1 - (node_memory_MemAvailable_bytes{job="node-exporter"} / node_memory_MemTotal_bytes{job="node-exporter"})) > 0.8
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Node {{ $labels.node }} has RAM usage >80%"
      description: 'RAM usage is currently {{ $value | humanizePercentage }} on {{ $labels.node }}'
