apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  GF_SERVER_ROOT_URL: "https://grafana.hyperserver.dev/"
  GF_ALERTING_ENABLED: "false"
  GF_LOG_LEVEL: "debug"

  GF_DATABASE_TYPE: "postgres"
  GF_DATABASE_HOST: "${POSTGRES_SERVICE_HOST}:${POSTGRES_SERVICE_PORT}"
  GF_DATABASE_NAME: "grafana"
  GF_DATABASE_USER: "grafana"

  GF_AUTH_DISABLE_LOGIN_FORM: "true"

  GF_AUTH_GITHUB_ENABLED: "true"
  GF_AUTH_GITHUB_SCOPES: "user:email,read:org"
  GF_AUTH_GITHUB_AUTH_URL: "https://github.com/login/oauth/authorize"
  GF_AUTH_GITHUB_TOKEN_URL: "https://github.com/login/oauth/access_token"
  GF_AUTH_GITHUB_API_URL: "https://api.github.com/user"
  GF_AUTH_GITHUB_TEAM_IDS: "10028644"
  GF_AUTH_GITHUB_ALLOW_SIGN_UP: "true"
  GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS: "q-homelab"
  GF_AUTH_GITHUB_ROLE_ATTRIBUTE_PATH: "[login=='mohammedgqudah'][0] && 'GrafanaAdmin' || 'Viewer'"

  GF_PATHS_PROVISIONING: "/etc/provisioning"

