apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    root_url = https://grafana.hyperserver.dev/

    [alerting]
    ; I use alertmanager for alerting
    enabled = false

    [security]
    admin_user = admin
    
    [database]
    type = postgres
    host = $__env{POSTGRES_SERVICE_HOST}:$__env{POSTGRES_SERVICE_PORT}
    name = grafana
    user = grafana

    [auth]
    disable_login_form = true

    [auth.github]
    enabled = true
    scopts = user:email,read:org
    auth_url = https://github.com/login/oauth/authorize
    token_url = https://github.com/login/oauth/access_token
    api_url = https://api.github.com/user
    ; # get the team ID from the GH rest API or GH cli
    team_ids = "10028644"
    allow_sign_up = true
    allowed_organizations = ["q-homelab"]
    client_id = "d1e188686b10e5899b56"
