apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage
  labels:
    app: postgres
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
