authentik:
    secret_key: file:///secrets/secret-key 
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true

    postgresql:
        host: postgres.default.svc.cluster.local
        user: file:///secrets/postgres-username
        password: file:///secrets/postgres-password

    redis:
      host: redis.default.svc.cluster.local
      user: file:///secrets/redis-username
      password: file:///secrets/redis-password

server:
    volumes:
      - name: authentik-secret
        secret:
          secretName: authentik-secret
    volumeMounts:
      - name: authentik-secret
        mountPath: /secrets
        readOnly: true
    ingress:
        ingressClassName: nginx
        enabled: true
        hosts:
            - auth.hyperserver.dev

worker:
    volumes:
      - name: authentik-secret
        secret:
          secretName: authentik-secret
    volumeMounts:
      - name: authentik-secret
        mountPath: /secrets
        readOnly: true
