apiVersion: v1
kind: ServiceAccount
metadata:
  name: d5dk8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d5dk8s-discoverer
roleRef:
  # this cluster role is defined in the prometheus service-account
  # I should extract it to a different file later.
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: discoverer
subjects:
- kind: ServiceAccount
  name: d5dk8s
  namespace: default
