kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: n8n-storage
  labels:
    app: n8n
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
