apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://prometheus.default.svc.cluster.local:9090'
    basicAuth: false

  - name: Alertmanager
    type: alertmanager
    url: 'http://alertmanager.default.svc.cluster.local:9093'
    access: proxy
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
    basicAuth: false
