apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  selector:
    name: node-exporter
  ports:
    - name: metrics
      targetPort: metrics
      port: 80
