alertmanager_version: latest

alertmanager_receivers:
  - name: discord
    discord_configs:
      - send_resolved: true
        webhook_url: "{{ alertmanager_discord_webhook_url }}"

alertmanager_route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  receiver: discord
