# use rules in roles/prometheus/rules/
prometheus_alert_rules_files:
  - rules/*.rules

prometheus_alertmanager_config:
  - scheme: http
    basic_auth:
      username: prom
      password: "{{ alertmanager_password }}"
    static_configs:
      - targets: ["{{ inventory_hostname }}:9093"]

prometheus_targets:
  node:
  # TODO: use ansible_hosts
  - targets:
    - 192.168.100.2:9100
    - 64.23.177.184:9100
    - 165.227.137.4:9100
    - pi-01.local:9100
    - pi-02.local:9100

prometheus_scrape_configs:
  - job_name: "node"
    basic_auth:
      username: prom
      password: "{{ prometheus_node_exporter_password }}"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"
