apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-storage
  labels:
    app: uptime-kuma
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
