controller:
  config:
    enable-real-ip: true
    forwarded-for-header: cf-connecting-ip
    use-forwarded-headers: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
