apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: postgres-exporter
  ports:
    - name: metrics
      port: 80
      targetPort: metrics
