kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bookstack-storage
  labels:
    app: bookstack
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
