apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: kube-state-metrics
  ports:
    - port: 80
      targetPort: metrics
      name: metrics
