apiVersion: v1
kind: Service
metadata:
  name: outline
  annotations:
    prometheus.io/probe: 'true'
spec:
  selector:
    app: outline
  ports:
    - name: outline
      port: 80
      targetPort: outline
