kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-storage
  labels:
    app: prometheus
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
