apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-inspector-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-inspector-bot-discoverer
roleRef:
  # this cluster role is defined in the prometheus service-account
  # I should extract it to a different file later.
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: discoverer
subjects:
- kind: ServiceAccount
  name: kube-inspector-bot
  namespace: default
