kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pastebin-storage
  labels:
    app: pastebin
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
