kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: loki-storage
  labels:
    app: loki
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
